Repository opensim-org/opensim-core, pull requests merged in 2018-02, with the labels that each got.

#2077 Fix InverseKinematicsTool to respect user time range
  OpenSim/Common/TimeSeriesTable.h
  OpenSim/Tools/InverseKinematicsTool.cpp
Labels: Quick Review, bug

#2090 Updated "Copyright and License" page
  doc/OpenSimDoxygenMain.dox
Labels: Documentation, Quick Review

#2093 Fix doxygen comments
  OpenSim/ExampleComponents/ToyPropMyoController.h
  OpenSim/ExampleComponents/ToyReflexController.h
Labels: Documentation, Quick Review

#2104 Fix typo in user-facing property description [ci skip]
  OpenSim/Simulation/Model/AbstractTool.cpp
Labels: Quick Review
