Repository opensim-org/opensim-core, pull requests merged in 2018-10, with the labels that each got.

#2297 updated WrapSphereObst
  OpenSim/Simulation/Wrap/WrapSphereObst.cpp
  OpenSim/Simulation/Wrap/WrapSphereObst.h
Labels: Quick Review

#2337 [doxygen] Fixed typos
  OpenSim/Simulation/Control/PrescribedController.h
Labels: Documentation, Quick Review

#2332 ExternalLoads itself finds datasource local to external loads (XML) file
  OpenSim/Simulation/Model/AbstractTool.cpp
  OpenSim/Simulation/Model/AbstractTool.h
  OpenSim/Simulation/Model/ExternalLoads.cpp
  OpenSim/Tools/DynamicsTool.cpp
  OpenSim/Tools/DynamicsTool.h
  OpenSim/Tools/InverseDynamicsTool.cpp
Labels: Quick Review, Tools
