Repository opensim-org/opensim-core, pull requests merged in 2019-05, with the labels that each got.

#2439 Update citation in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#2461 Prevent spurious doxygen autolink [ci skip]
  OpenSim/Common/C3DFileAdapter.h
Labels: Documentation, Quick Review

#2475 Enable users to "press any key" to quit in the visualizer
  OpenSim/Simulation/OpenSense/OpenSenseUtilities.cpp
Labels: Quick Review, opensense
